### ISSUE TITLE
Use inheritance to json validation and user auth

### ISSUE THREAD

**Issue by MarneeDear** [Elmerly/back-end-api#38]
Consider the abstract base class pattern

**Comment by MarneeDear** [comment]
Do not use the abstract base class pattern.  Conversations with yourself on Github are funny.

**Comment by julianpistorius** [comment]
Yes. :)

**Comment by MarneeDear** [comment]
self.we_are_not_allone == True
self.hide()

**Comment by christru** [comment]
Else:
self.rejoice()

**Comment by MarneeDear** [comment]
:)
